# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

os_yum_base_packages: "vim-common,curl,yum-utils,device-mapper-persistent-data,lvm2,python2-pip,wget,bridge-utils,boost-devel,openssl-devel,pcre-devel,zlib-devel,glib2-devel,autoconf,automake,libtool,flex,bison,git,cmake,pciutils,python-websocket-client,jsoncpp-devel,fcgi-devel,hiredis-devel,numactl-devel,gcc-c++,psmisc,python-httplib2,pixman-devel,moreutils,jq,python-devel,createrepo"
os_yum_exclude_rpm_packages: "exclude=kernel-3* kernel-rt* kernel-rt-kvm* kernel-rt-devel*"
os_remove_yum_plugins: true

git_repo_url: https://{{ git_repo_token }}@github.com/open-ness/edgenode.git
git_repo_branch: master
git_repo_dest: /opt/edgenode

offline_path: "{{ offline_path_common }}/node"
offline_archive: "offline-node.tar.gz"

offline_download_kernel: true
