# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- include_tasks: cleanup.yml
- include_tasks: prebuild.yml
- include_tasks: build.yml
- include_tasks: deploy.yml

- name: set up dataplane
  include_role:
    name: "openness/onprem/dataplane/{{ onprem_dataplane }}/worker"

- include_tasks: bringup.yml
