# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: Add excludes (rpm packages) to yum.conf
  lineinfile:
    dest: /etc/yum.conf
    line: "{{ _os_yum_exclude_rpm_packages }}"
    insertafter: EOF
  when:
    - _os_yum_exclude_rpm_packages is defined
    - _os_yum_exclude_rpm_packages|length > 0
