# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- block:
  - name: copy log_collector to the controller
    copy:
      src: ./scripts/log_collector{{ item.ext }}
      dest: "{{ ansible_facts.user_dir }}/log_collector{{ item.ext }}"
      mode: "{{ item.mode }}"
    with_items:
    - { ext: "", mode: "0755"}
    - { ext: ".json", mode: "0644"}

  - name: collect logs
    command: "{{ ansible_facts.user_dir }}/log_collector --force"
    args:
      chdir: "{{ ansible_facts.user_dir }}"
    become: yes

  - name: create var for filename
    set_fact:
      log_filename: ./failed_readiness_logs_{{ ansible_date_time.iso8601_basic_short }}.tar.gz

  - name: get logs from remote
    fetch:
      src: "{{ ansible_facts.user_dir }}/Result.tar.gz"
      dest: "{{ log_filename }}"
      flat: yes

  delegate_to: "{{ groups['controller_group'][0] }}"
  run_once: true

