# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: check common settings
  include_tasks: settings_check_common.yml

- name: validate requested CNIs
  include_tasks: "../roles/kubernetes/cni/tasks/precheck.yml"

- name: biosfw role - verify precondition
  block:
  - name: load biosfw vars
    include_vars:
      file: "{{ role_path }}/defaults/main.yml"
      name: defaults
  - name: check syscfg_package.zip
    stat:
      path: "{{ defaults._syscfg_local_path }}"
    delegate_to: localhost
    register: biosfw_syscfg_package_stat
  - name: fail if file not present
    fail:
      msg: |
        BIOSFW feature enabled, but the SYSCFG package is missing.
        It is expected in: {{ defaults._syscfg_local_path }}
    when: not biosfw_syscfg_package_stat.stat.exists
  when:
  - ne_biosfw_enable | default(False)
  - not offline_enable | default(False)
  vars:
    role_path: "{{ playbook_dir }}/roles/kubernetes/biosfw/node"
- name: check VT-d open in bios
  block:
  - debug:
      msg: "Expected VT-d - ENABLED,if failed please check bios"
  - name: check VT-d status
    shell: ls /sys/kernel/iommu_groups/0/devices/0000:00:00.0
  when: vtd_bios_check | default(False)

- name: e810 role - verify precondition
  block:
  - name: load e810 vars
    include_vars:
      file: "{{ role_path }}/defaults/main.yml"
      name: defaults
  - name: check ice<x>tar.gz
    stat:
      path: "{{ defaults._ice_local_path }}"
    delegate_to: localhost
    register: ice_package_stat

  - name: check iavf<x>tar.gz
    stat:
      path: "{{ defaults._iavf_local_path }}"
    delegate_to: localhost
    register: iavf_package_stat

  - name: fail if file not present
    fail:
      msg: |
        E810 support enabled, but the iavf or ice package is missing.
        It is expected in: {{ defaults._ice_local_path }} and {{ defaults._iavf_local_path }}
    when: not ice_package_stat.stat.exists or not iavf_package_stat.stat.exists
  when:
  - e810_driver_enable | default(False)
  - not offline_enable | default(False)
  vars:
    role_path: "{{ playbook_dir }}/roles/infrastructure/e810_driver_update"

- name: check Hyperthreading state
  block:
  - name: check current state
    shell: set -o pipefail && lscpu | grep "Thread(s) per core" | awk '{print $NF}'
    register: ht
  - name: fail if Hyperthreading is ENABLED instead of DISABLED
    fail:
      msg: |
        Expected deployment Hyperthreading state - DISABLED.
        Current Hyperthreading state - ENABLED.
    when: expected_hyperthreading_state  == "disabled" and ht.stdout != "1"
  - name: fail if Hyperthreading is DISABLED instead of ENABLED
    fail:
      msg: |
        Expected deployment Hyperthreading state - ENABLED.
        Current Hyperthreading state - DISABLED.
    when: expected_hyperthreading_state == "enabled" and ht.stdout != "2"
  when: check_hyperthreading | bool
