# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
_pv_dir: "{{ openness_dir }}/pv/prometheus"
_pv_names:
  - prometheus-volume

_prometheus_chart_dir: "{{ ne_helm_charts_default_dir }}/prometheus"
_prometheus_chart_commit: "prometheus-13.3.3"
_prometheus_chart_url: "https://raw.githubusercontent.com/prometheus-community/helm-charts/{{ _prometheus_chart_commit }}/charts/prometheus/"

_prometheus_chart:
  - ".helmignore"
  - "Chart.yaml"
  - "values.yaml"

_prometheus_chart_templates:
  - "templates/NOTES.txt"
  - "templates/_helpers.tpl"
  # - "templates/alertmanager/clusterrole.yaml"
  # - "templates/alertmanager/clusterrolebinding.yaml"
  # - "templates/alertmanager/cm.yaml"
  # - "templates/alertmanager/deployment.yaml"
  # - "templates/alertmanager/headless-svc.yaml"
  # - "templates/alertmanager/ingress.yaml"
  # - "templates/alertmanager/netpol.yaml"
  # - "templates/alertmanager/pdb.yaml"
  # - "templates/alertmanager/psp.yaml"
  # - "templates/alertmanager/pvc.yaml"
  # - "templates/alertmanager/role.yaml"
  # - "templates/alertmanager/service.yaml"
  # - "templates/alertmanager/serviceaccount.yaml"
  # - "templates/alertmanager/sts.yaml"
  - "templates/node-exporter/daemonset.yaml"
  - "templates/node-exporter/psp.yaml"
  - "templates/node-exporter/role.yaml"
  - "templates/node-exporter/rolebinding.yaml"
  - "templates/node-exporter/svc.yaml"
  - "templates/node-exporter/serviceaccount.yaml"
  # - "templates/pushgateway/clusterrole.yaml"
  # - "templates/pushgateway/clusterrolebinding.yaml"
  # - "templates/pushgateway/deploy.yaml"
  # - "templates/pushgateway/ingress.yaml"
  # - "templates/pushgateway/netpol.yaml"
  # - "templates/pushgateway/pdb.yaml"
  # - "templates/pushgateway/psp.yaml"
  # - "templates/pushgateway/pvc.yaml"
  # - "templates/pushgateway/service.yaml"
  # - "templates/pushgateway/serviceaccount.yaml"
  - "templates/server/clusterrole.yaml"
  - "templates/server/clusterrolebinding.yaml"
  - "templates/server/cm.yaml"
  - "templates/server/deploy.yaml"
  - "templates/server/headless-svc.yaml"
  - "templates/server/ingress.yaml"
  - "templates/server/netpol.yaml"
  - "templates/server/pdb.yaml"
  - "templates/server/psp.yaml"
  - "templates/server/pvc.yaml"
  - "templates/server/rolebinding.yaml"
  - "templates/server/service.yaml"
  - "templates/server/serviceaccount.yaml"
  - "templates/server/sts.yaml"
  - "templates/server/vpa.yaml"

_prometheus_dependency_charts:
  - "charts/kube-state-metrics/.helmignore"
  - "charts/kube-state-metrics/Chart.yaml"
  - "charts/kube-state-metrics/values.yaml"
  - "charts/kube-state-metrics/templates/clusterrolebinding.yaml"
  - "charts/kube-state-metrics/templates/clusterrole.yaml"
  - "charts/kube-state-metrics/templates/deployment.yaml"
  - "charts/kube-state-metrics/templates/_helpers.tpl"
  - "charts/kube-state-metrics/templates/kubeconfig-secret.yaml"
  - "charts/kube-state-metrics/templates/NOTES.txt"
  - "charts/kube-state-metrics/templates/pdb.yaml"
  - "charts/kube-state-metrics/templates/podsecuritypolicy.yaml"
  - "charts/kube-state-metrics/templates/psp-clusterrolebinding.yaml"
  - "charts/kube-state-metrics/templates/psp-clusterrole.yaml"
  - "charts/kube-state-metrics/templates/serviceaccount.yaml"
  - "charts/kube-state-metrics/templates/servicemonitor.yaml"
  - "charts/kube-state-metrics/templates/service.yaml"
  - "charts/kube-state-metrics/templates/stsdiscovery-rolebinding.yaml"
  - "charts/kube-state-metrics/templates/stsdiscovery-role.yaml"
