# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: NFD master firewall rule
  ignore_errors: yes
  firewalld:
    port: 8082/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: reload firewall rules
  command: firewall-cmd --reload
  changed_when: false

- name: offline | load NFD docker image
  docker_image:
    name: nfd-master
    load_path: "{{ _offline_docker_images_path }}/nfd-master.tar"
    source: load
  when: _offline_mode

- name: build NFD master image
  block:
  - name: create temporary custom .openness_gitconfig
    include_tasks: ../../../../git_repo/tasks/gitconfig_bootstrap.yml
  - name: build NFD master binary
    shell: source /etc/profile && go build -o dist/nfd-master ./cmd/nfd-master
    args:
      chdir: "{{ _git_repo_dest }}"
      creates: "{{ _git_repo_dest }}/dist/nfd-master"
  - name: build Docker image
    command: docker-compose build nfd-master
    args:
      chdir: "{{ _git_repo_dest }}"
  always:
  - name: remove temporary .openness_gitconfig
    include_tasks: ../../../../git_repo/tasks/gitconfig_remove.yml
  when: not _offline_mode

- name: bring up NFD master
  command: docker-compose up -d --no-build nfd-master
  args:
    chdir: "{{ _git_repo_dest }}"
  changed_when: true
