# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: permit WeaveNet ports in firewall
  ignore_errors: yes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
  - 6783/tcp
  - 6783/udp
  - 6784/udp

- name: apply WeaveNet via the addon
  shell: set -o pipefail && kubectl apply -f "{{ _weavenet_yaml }}"
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"
  changed_when: true

- name: wait for weavenet pods become running
  shell: set -o pipefail && kubectl get pods -n kube-system -l name=weave-net | awk '$3=="Running"'
  register: weavenet_pods_running
  retries: 30
  delay: 10
  until: weavenet_pods_running.rc == 0
  changed_when: false
