# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---

- name: check if packages installed in proper version
  shell: rpm -q openvswitch ovn ovn-common | grep {{ ovn_version }} | wc -l
  args:
    warn: false
  register: rpm_grep
  changed_when: false

- name: (re)install openvswitch tools if needed
  block:
  - name: remove old packages
    yum:
      name: "{{ ovn_packages_to_remove }}"
      state: absent
  - name: install OVN tools dependencies
    yum:
      name: "{{ ovn_packages_yum }}"
      state: installed
      update_cache: yes
      allow_downgrade: true
      validate_certs: no
  - name: install OVN tools
    command: "yum install -y {{ ovn_packages_urls | join(' ') }}"
    args:
      warn: false
  when: "'3' not in rpm_grep.stdout"

- name: open kube-ovn firewall rules
  ignore_errors: yes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
  - 6641/tcp
  - 6642/tcp
  - 6081/udp

- name: apply kube-ovn
  command: "kubectl apply -f {{ item }}"
  with_items: "{{ kubeovn_yamls }}"
  changed_when: true

- name: Wait till k8s master starts
  shell: kubectl get nodes {{ ansible_hostname }} | awk '$2=="Ready"'
  register: k8s_master_init_start
  retries: 30
  delay: 10
  until: k8s_master_init_start.rc == 0
  changed_when: false
