# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cdi-upload-proxy-policy
  namespace: default
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          ns: cdi
    ports:
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      app: containerized-data-importer
  policyTypes:
  - Ingress
