# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

_config_patch: default_config.patch
_master_clock: "{{ 'CLOCK_REALTIME' if ptp_port_gm is not defined or ptp_port_gm is none else ptp_port_gm }}"

