# SPDX-License-Identifier: Apache-2.0
# Copyright Â© 2019 Intel Corporation

---

- name: include common vars
  include_vars: ../../common/defaults/main.yml

- name: prepare firewall
  include_tasks: add_firewall_rules.yml

- name: create directory for certs used by AF and NEF
  file:
    name: "{{ certs_dest }}/ngc"
    state: directory

- name: copy genCerts.json file
  copy:
    src: "{{ git_repo_ngc_dir }}/scripts/genCerts.sh"
    remote_src: yes
    dest: "{{ certs_dest }}/ngc"
    mode: a+x

- name: run script to generate cerificates
  shell: './genCerts.sh -t IP -h {{ controller_ip }} -t DNS -h {{ controller_name }}' # noqa 305
  args:
    chdir: "{{ certs_dest }}/ngc"
  changed_when: true

- include_tasks: subtasks/bringup_oam.yml

- include_tasks: subtasks/bringup_nef.yml

- include_tasks: subtasks/bringup_af.yml

