# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

_istio_main_dir: "/opt/istio"

_istio_version: "1.6.8"
_istio_base_url: "https://istio.io/downloadIstio"
_istio_dest_dir: "{{ _istio_main_dir }}/istio-{{ _istio_version }}"

smi_commit: "e1a19b01845b7c41302018080511a9973be74e7c"
_smi_crds_yaml: "https://raw.githubusercontent.com/servicemeshinterface/smi-adapter-istio/{{ smi_commit }}/deploy/crds/crds.yaml"
_smi_operator_yaml: "https://raw.githubusercontent.com/servicemeshinterface/smi-adapter-istio/{{ smi_commit }}/deploy/operator-and-rbac.yaml"
