# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: check if ion module already installed
  stat:
    path: /sys/module/myd_ion
  register: ion

- name: check if vsc module already installed
  stat:
    path: /sys/module/myd_vsc
  register: vsc

- name: check if udev rules already installed
  stat:
    path: /etc/udev/rules.d/99-hddl-ion.rules
  register: udev

- name: download and install OpenVino if modules and udevs not there
  block:
  - name: create /temp
    file:
      path: "/temp"
      state: directory
  - name: check if already downloaded
    stat:
      path: "{{ _openvino_download_dir }}"
    register: ov_dl_dir
  - name: download OpenVino - may take a while (~750MB file)
    get_url:
      url: "{{ _openvino_url }}"
      dest: "{{ _openvino_download_dest }}"
    when:
    - not ov_dl_dir.stat.exists
  - name: ensure download dir exists
    file:
      path: "{{ _openvino_download_dir }}"
      state: directory
  - name: extract OpenVino
    unarchive:
      src: "{{ _openvino_download_dest }}"
      dest: "{{ _openvino_download_dir }}"
      extra_opts: "--strip-components=1"
      remote_src: yes
      creates: "{{ _openvino_silent_config }}"
  - name: configure licence agreement
    lineinfile:
      path: "{{ _openvino_silent_config }}"
      regexp: '^ACCEPT_EULA='
      line: ACCEPT_EULA=accept
  - name: install OpenVino
    command: "{{ _openvino_install_command }}"
    args:
      chdir: "{{ _openvino_download_dir }}"
  - name: install OpenVino kernel drivers and udev rules
    shell: "{{ _openvino_hddl_dependency_install }}" # noqa 305
  when: not udev.stat.exists or not vsc.stat.exists or not ion.stat.exists

- name: build HDDL image
  block:
  - name: create temporary custom .openness_gitconfig
    include_tasks: ../../../../git_repo/tasks/gitconfig_bootstrap.yml
  - name: build HDDL
    shell: source /etc/profile && make hddllog
    args:
      chdir: "{{ _git_repo_dest }}"
  always:
  - name: remove temporary .openness_gitconfig
    include_tasks: ../../../../git_repo/tasks/gitconfig_remove.yml

- name: bring up hddlservice container
  command: "docker-compose up -d --no-build hddlservice"
  args:
    chdir: "{{ _git_repo_dest }}/build/hddlservice"
  environment:
    VER: "{{ _docker_hddlservice_tag }}"
  changed_when: true

- name: wait until VPU is bound to Myriad driver
  wait_for:
    path: /dev/myriad0
