# SPDX-License-Identifier: Apache-2.0
# Copyright Â© 2019 Intel Corporation

---


- block:
  - name: create temporary custom .openness_gitconfig
    include_tasks: ../../../git_repo/tasks/gitconfig_bootstrap.yml
  - name: build OAM component
    shell: source /etc/profile && make oam
    args:
      chdir: "{{ git_repo_ngc_dir }}"
  always:
    - name: remove .openness_gitconfig
      include_tasks: ../../../git_repo/tasks/gitconfig_remove.yml
  when: not offline_mode

- name: copy oam binaries to build folder
  copy:
    src: "{{ git_repo_ngc_dist_dir }}/oam"
    remote_src: yes
    dest: "{{ git_repo_ngc_build_dir }}/onprem/oam"
  when: not offline_mode

- name: copy oam.json configuration file
  copy:
    src: "{{ git_repo_ngc_dir }}/configs/oam.json"
    remote_src: yes
    dest: "{{ configs_dest }}/ngc"

- name: update af config file
  shell: >
    set -o pipefail &&
    jq '.UIEndpoint="http://{{ controller_ip }}:3020"' /etc/openness/configs/ngc/oam.json |
    sponge /etc/openness/configs/ngc/oam.json
  args:
  changed_when: true

- name: check Docker service
  command: systemctl status docker
  ignore_errors: true
  changed_when: false
  args:
    warn: false
  register: docker_service_status

- name: build OAM docker image
  docker_image:
    name: oam-image:1.0
    source: build
    build:
      path: "{{ git_repo_ngc_build_dir }}/onprem/oam"
      pull: yes
      use_config_proxy: yes
  when: docker_service_status.rc == 0 and not offline_mode

- name: Run OAM container
  docker_container:
    name: oam-container
    image: oam-image:1.0
    state: started
    published_ports:
      - 8070:8070
    volumes:
      - "{{ certs_dest }}/ngc:/etc/certs:rw"
      - "{{ configs_dest }}/ngc:/root/configs:rw"
  when: docker_service_status.rc == 0 and ngc_test_prepare is not defined
