# SPDX-License-Identifier: Apache-2.0
# Copyright Â© 2019-2020 Intel Corporation

---

- block:
  - name: create temporary custom .openness_gitconfig
    include_tasks: ../../../git_repo/tasks/gitconfig_bootstrap.yml
  - name: build NEF component
    shell: source /etc/profile && make nef
    args:
      chdir: "{{ git_repo_ngc_dir }}"
  always:
    - name: remove .openness_gitconfig
      include_tasks: ../../../git_repo/tasks/gitconfig_remove.yml
  when: not offline_mode

- name: copy nef binaries to build folder
  copy:
    src: "{{ git_repo_ngc_dist_dir }}/nef"
    remote_src: yes
    dest: "{{ git_repo_ngc_build_dir }}/onprem/nef"
  when: not offline_mode

- name: copy nef.json configuration file
  copy:
    src: "{{ git_repo_ngc_dir }}/configs/nef.json"
    remote_src: yes
    dest: "{{ configs_dest }}/ngc"

- name: copy oauth2.json configuration file
  copy:
    src: "{{ git_repo_ngc_dir }}/configs/oauth2.json"
    remote_src: yes
    dest: "{{ configs_dest }}/ngc"

- name: check Docker service
  command: systemctl status docker
  ignore_errors: true
  changed_when: false
  args:
    warn: false
  register: docker_service_status

- name: build NEF docker image
  docker_image:
    name: nef-image:1.0
    source: build
    build:
      path: "{{ git_repo_ngc_build_dir }}/onprem/nef"
      pull: yes
      use_config_proxy: yes
  when: docker_service_status.rc == 0 and not offline_mode

- name: run NEF container
  docker_container:
    name: nef-container
    image: nef-image:1.0
    state: started
    volumes:
      - "{{ certs_dest }}/ngc:/etc/certs:rw"
      - "{{ configs_dest }}/ngc:/root/configs:rw"
    published_ports:
      - 8060:8060
  when: docker_service_status.rc == 0 and ngc_test_prepare is not defined

- name: update container's /etc/hosts file
  shell: >
    set -o pipefail &&
    docker exec -t nef-container /bin/bash -c "echo {{ controller_ip }}
    {{ controller_name }} | tee -a /etc/hosts"
  args:
  when:  ngc_test_prepare is not defined
