# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: generate Dockerfile from template
  template:
    src: Dockerfile.j2
    dest: "{{ _dpdk_install_dir }}/Dockerfile"

- name: copy .dockerignore
  copy:
    src: .dockerignore
    dest: "{{ _dpdk_install_dir }}/.dockerignore"

- name: copy configure_ovn_net.sh
  copy:
    src: configure_ovn_net.sh
    dest: "{{ _dpdk_install_dir }}/configure_ovn_net.sh"

- name: generate start_ovs_ovn.sh from template
  template:
    src: start_ovs_ovn.sh.j2
    dest: "{{ _dpdk_install_dir }}/start_ovs_ovn.sh"
    mode: '0744'

#TODO: Use variables(Currently defined in configure_ovn_net.sh)
#TODO: Find a working solution for selective masquerade
- name: Add firewall rules for OVN masquerade
  command: firewall-cmd --zone=public --add-masquerade --permanent
  ignore_errors: yes
  changed_when: true

- name: Add firewall rules to accept ovn-local interface
  command: firewall-cmd --permanent --zone=trusted --change-interface=ovn-local
  ignore_errors: yes
  changed_when: true

- name: Reload firewall rules
  command: firewall-cmd --reload
  ignore_errors: yes
  changed_when: true
