# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: 00-multus.conf should be present
  stat:
    path: /etc/cni/net.d/00-multus.conf
  register: this
  failed_when: not this.stat.exists
  changed_when: false

