# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: include common vars
  include_vars: ../common/defaults/main.yml

- name: build OVS-DPDK images
  block:
    - name: build OVS-DPDK image (this may take some time...)
      docker_image:
        name: ovs-ovn
        source: build
        state: present
        force_source: yes
        build:
          path: "{{ _dpdk_install_dir }}"
          dockerfile: Dockerfile
          pull: yes
          use_config_proxy: yes

    - name: Clean docker image files from dpdk directory
      file:
        state: absent
        path: "{{ _dpdk_install_dir }}/{{ item }}"
      with_items: "{{ _dockerimage_files_to_rm }}"

- name: open ovn firewall rules
  ignore_errors: yes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
  - 6641/tcp
  - 6642/tcp
  - 6081/udp

- name: run ovn-ovs container
  docker_container:
    name: ovs-ovn
    image: ovs-ovn
    privileged: yes
    network_mode: host
    published_ports:
      - 6641:6641
      - 6642:6642
      - 6081:6081/udp
    volumes:
      - "{{ _huge_dir }}:{{ _huge_dir }}:rw"
      - "{{ _ovs_dir }}:{{ _ovs_dir }}:rw"
      - /dev:/dev:rw
      - /lib/modules:/lib/modules:rw
    memory: "{{ ovncni_dpdk_resource_limits }}"

- name: wait for OVN DB socket
  wait_for:
    path: /var/run/openvswitch/ovnnb_db.sock
    timeout: 600
  changed_when: false

- name: deploy OVN CNI configuration
  block:
  - name: create artifacts/controller/cni directory
    file:
      path: "{{ _git_repo_dest }}/artifacts/controller/cni"
      state: directory
  - name: copy config files to edgecontroller/artifacts/controller/cni
    copy:
      src: "{{ item }}"
      dest: "{{ _git_repo_dest }}/artifacts/controller/cni"
    with_items:
    - cni_args.json
    - cni.conf
