# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: cleanup harbor helm
  command: helm uninstall harbor-app -n harbor
  register: del_result
  until: del_result.rc == 0
  retries: 3
  delay: 5
  changed_when: false
  ignore_errors: true

- name: delete harbor PV and PVC
  command: kubectl delete -f disks.yaml
  args:
    chdir: "{{ _git_repo_dest_harbor }}"
  changed_when: false
  ignore_errors: true

- name: delete harbor data
  file:
    path: "{{ _harbor_pv_dir }}"
    state: absent
  ignore_errors: yes

- name: delete certificate from controller machine
  file:
    path: "/etc/docker/certs.d/{{ _registry_ip_address }}:{{ _registry_port }}"
    state: absent
  ignore_errors: yes

- name: delete harbor-registry file
  file:
    path: "{{ _git_repo_dest_harbor }}"
    state: absent
  ignore_errors: yes