# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

dependencies:
- role: machine_setup/grub
- role: machine_setup/conditional_reboot
- role: dpdk
- role: openness/onprem/dataplane/ovncni/common
