# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
- name: include time/verify/defaults vars
  include_vars: ../../verify/defaults/main.yml

- name: stop and disable chronyd service if available
  systemd:
    name: chronyd
    enabled: no
    masked: no
    state: stopped
    daemon_reload: yes
  become: yes
  ignore_errors: yes

- name: install ntp daemon
  yum:
    name: ntp
    state: present
    skip_broken: yes
  become: yes

- name: set custom ntp servers
  block:
    - name: disable default servers
      lineinfile:
        dest: /etc/ntp.conf
        regexp: "^server.*"
        state: absent
      become: yes
    - name: prepare values
      set_fact:
        servers_prepared: "{{ ntp_servers | map('regex_replace', '(.*)', 'server \\1 iburst') | join('\n') }}"
    - name: add custom ntp server to ntp config
      blockinfile:
        path: /etc/ntp.conf
        block: |
          {{ servers_prepared }}
        insertafter: "Please consider joining the pool.*"
      become: yes
  when: (ntp_servers | length) > 0

- name: update time, enable ntpd service and set hardware clock
  block:
    - name: temporarily stop ntpd service
      systemd:
        name: ntpd
        enabled: yes
        masked: no
        state: stopped
        daemon_reload: yes
      become: yes
    - name: kill all ntpd processes
      command: killall ntpd
      become: yes
      ignore_errors: yes
    - name: update time
      command: ntpd -gq
      become: yes
    - name: enable and start ntpd service
      systemd:
        name: ntpd
        enabled: yes
        masked: no
        state: restarted
        daemon_reload: yes
      become: yes
    - name: set hardware clock
      command: hwclock -w
      become: yes
    - name: create ntp time set flag
      file:
        path: "{{ _ntp_time_set }}"
        state: touch
      become: yes
