# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---
- name: make sure .docker directory exists
  file:
    name: .docker
    state: directory

- name: check if previous docker config exists
  stat:
    path: .docker/config.json
  register: docker_user_config_file

- name: create .docker/temp-proxy.json from template
  template:
    src: config.json.j2
    dest: .docker/temp-proxy.json

- name: add proxy to already existing config.json
  block:
    - name: add proxy to already existing config.json
      shell: "jq -s '.[0] + .[1]' .docker/config.json .docker/temp-proxy.json | sponge .docker/config.json"
    - name: remove temporary .docker/temp-proxy.json
      file:
        path: .docker/temp-proxy.json
        state: absent
  when: docker_user_config_file.stat.exists

- name: rename temp-proxy.json to config.json
  command: mv .docker/temp-proxy.json .docker/config.json
  args:
    creates: .docker/config.json
  when: not docker_user_config_file.stat.exists

- name: create http-proxy.conf for docker service
  block:
    - name: create Docker system config directory
      file:
        name: /etc/systemd/system/docker.service.d
        state: directory
      become: yes
    - name: create http-proxy.conf from template
      template:
        src: http-proxy.conf.j2
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
      become: yes
      notify:
        - enable and start docker service
