# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: check istio deployments
  check_k8s_object:
    kind: deployment
    name: "{{ item }}"
    namespace: istio-system
  with_items:
  - istio-ingressgateway
  - istiod
  - kiali
  - smi-adapter-istio

