# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: get number of VCA nodes
  shell: set -o pipefail && vcactl status | grep Card | wc -l
  changed_when: true
  register: num_vca
  become: yes

- debug: msg="Detected {{ num_vca.stdout | int }} VCAC-A cards"

- name: remove VCA node system image build directory
  file:
    path: "{{ _vca_dest }}/VCAC-A/Intel_Media_Analytics_Node/build/vcad/INSTALL/"
    state: absent
  when: force_build_enable|bool
  become: yes

- name: build system image of VCA node
  command: "./vcad_build.sh -c -o FULL --silent silent.cfg"
  args:
    creates: "{{ _vca_dest }}/VCAC-A/Intel_Media_Analytics_Node/build/vcad/INSTALL/"
    chdir: "{{ _vca_dest }}/VCAC-A/Intel_Media_Analytics_Node/scripts"
  ignore_errors: yes
  register: vcad_build_ret

- name: make sure build directory owned by ansible_user
  file:
    path: "{{ _vca_dest }}/VCAC-A/Intel_Media_Analytics_Node/build"
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ openness_user_group }}"
  become: yes

- name: check build system image of VCA node result
  fail:
    msg: "build system image of VCA node has failed because of errors."
  when: >
    (vcad_build_ret.stderr is defined) and
    (('ERROR' in vcad_build_ret.stderr) or
     ('Error' in vcad_build_ret.stderr) or
     ('error' in vcad_build_ret.stderr))

- name: unarchive VCAC-A vcad image
  command: "gzip -d {{ _vca_vcad_image }}.gz"
  args:
    chdir: "{{ _vca_dest }}/VCAC-A/Intel_Media_Analytics_Node/build/vcad/INSTALL/"
    creates: "{{ _vca_vcad_image }}"
  become: yes

- name: copy vcad image for multiple VCA cards
  copy:
    src: "{{ _vca_dest }}/VCAC-A/Intel_Media_Analytics_Node/build/vcad/INSTALL/{{ _vca_vcad_image }}"
    dest: "{{ _vca_dest }}/VCAC-A/Intel_Media_Analytics_Node/build/vcad/INSTALL/{{ vca_idx | int - 1 }}{{ _vca_vcad_image }}"
    remote_src: yes
    mode: preserve
  loop_control:
    loop_var: vca_idx
  with_sequence: count="{{ num_vca.stdout | int }}"
  become: yes

- name: copy vca init scripts
  copy:
    src: "{{ item }}"
    dest: "{{ _vca_dest }}"
    mode: a+x
  with_items:
    - init_vca.sh
    - shutdown_vca.sh
    - setup_firewall.sh

- name: unload VCAC-A vcad image
  shell: |
    "{{ _vca_dest }}/shutdown_vca.sh"
    vcactl blockio close {{ vca_idx | int - 1 }} 0 vcablk0
  changed_when: true
  loop_control:
    loop_var: vca_idx
  with_sequence: count="{{ num_vca.stdout | int }}"
  become: yes

- name: load VCAC-A vcad image
  command: "vcactl blockio open {{ vca_idx | int - 1 }} 0 vcablk0 RW {{ vca_idx | int - 1 }}{{ _vca_vcad_image }}"
  args:
    chdir: "{{ _vca_dest }}/VCAC-A/Intel_Media_Analytics_Node/build/vcad/INSTALL/"
  changed_when: true
  loop_control:
    loop_var: vca_idx
  with_sequence: count="{{ num_vca.stdout | int }}"
  become: yes

- name: configure VCAC-A node hostname
  command: "vcactl config {{ vca_idx | int - 1 }} 0 node-name {{ inventory_hostname | lower }}-vca{{ vca_idx }}"
  changed_when: true
  loop_control:
    loop_var: vca_idx
  with_sequence: count="{{ num_vca.stdout | int }}"
  become: yes

- name: set VCAC-A init script at system boot
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '^{{ _vca_dest }}'
    line: '{{ _vca_dest }}/init_vca.sh'
    insertafter: EOF
    mode: u+x,g+x,o+x
  become: yes

- name: initialize VCAC-A
  command: "{{ _vca_dest }}/init_vca.sh"
  register: init_vca
  failed_when: init_vca.rc != 0
  changed_when: init_vca.rc == 0
  become: yes

- name: update firewall settings for VCAC-A
  command: "{{ _vca_dest }}/setup_firewall.sh"
  register: setup_firewall
  failed_when: setup_firewall.rc != 0
  changed_when: setup_firewall.rc == 0
  become: yes

- debug: msg="{{ init_vca.stdout }}"

- name: configure all VCA nodes
  include_tasks: configure_vca_nodes.yml
  vars:
    vca_node_ip: "172.32.{{ vca_idx }}.1"
  loop_control:
    loop_var: vca_idx
  with_sequence: count="{{ num_vca.stdout | int }}"
