# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

_emco:
  repo: "https://github.com/otcshare/EMCO"
  commit: "{{ emco_commitID }}"
  dest: /opt/openness/emco
  registryPrefix: "{{ _registry_host }}:{{ _registry_port }}/intel/"
  buildCause: DEV_TEST
  emcoSrvRelease: latest
  release_name: emco-services
