# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

_acc100_dpdk_version: "20.11"
_acc100_dpdk_checksum: "13a990dc3b300635f685e268b36918a3"

_acc100_dpdk_name: "dpdk-{{ _acc100_dpdk_version }}"
_acc100_dpdk_install_dir: "/opt/{{ _acc100_dpdk_name }}"
_acc100_dpdk_init_dir: "{{ _acc100_dpdk_install_dir }}/app/test-bbdev/"

_acc100_dpdk_download_url: "http://fast.dpdk.org/rel/{{ _acc100_dpdk_name }}.tar.xz"
_acc100_dpdk_download_dest: "/tmp/{{ _acc100_dpdk_name }}.tar.xz"

# URL or package name providing kernel-devel package when role `custom_kernel` is disabled (commented) or skipped for specific host (`customize_kernel_skip` variable)
dpdk_kernel_devel: "http://linuxsoft.cern.ch/centos-vault/7.8.2003/os/x86_64/Packages/kernel-devel-3.10.0-1127.el7.x86_64.rpm"
